#!/usr/bin/env python3
"""Per-version GitHub Release download counts for olcrtc-ios (#307).

Sums ``release.assets[].download_count`` from the GitHub REST API and renders a
markdown table — one section per release tag, each asset's count plus a per-tag
and an all-time total. Run it locally (it uses your ``gh`` token if exported) or
from the ``download-stats.yml`` workflow (it uses ``GITHUB_TOKEN``).

Usage:
    python3 scripts/download-stats.py                      # print the table to stdout
    python3 scripts/download-stats.py --write docs/download-stats.md
    python3 scripts/download-stats.py --repo owner/name

Auth / rate limit: one ``GET /releases`` (paginated) per run — well within the
unauthenticated 60 req/h limit, but a token (``GH_TOKEN`` / ``GITHUB_TOKEN``)
raises it to 5000 req/h and is required for a private repo. Stdlib only, no
third-party dependencies (mirrors scripts/parity_check.py).
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone

API = "https://api.github.com"


def resolve_repo(arg: str | None) -> str:
    """owner/name from --repo, then $GITHUB_REPOSITORY, then the git origin URL."""
    if arg:
        return arg
    env = os.environ.get("GITHUB_REPOSITORY")
    if env:
        return env
    try:
        url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        url = ""
    # git@github.com:owner/repo.git  or  https://github.com/owner/repo(.git)
    m = re.search(r"github\.com[:/]([^/]+/[^/.]+)(?:\.git)?/?$", url)
    if m:
        return m.group(1)
    sys.exit("error: could not determine repo — pass --repo owner/name or set GITHUB_REPOSITORY")


def fetch_releases(repo: str, token: str | None) -> list[dict]:
    """All releases (newest-first), following pagination."""
    releases: list[dict] = []
    page = 1
    while True:
        url = f"{API}/repos/{repo}/releases?per_page=100&page={page}"
        req = urllib.request.Request(url)
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        try:
            with urllib.request.urlopen(req) as resp:
                batch = json.load(resp)
        except urllib.error.HTTPError as e:
            sys.exit(f"error: GitHub API {e.code} for {repo} — {e.reason}")
        except urllib.error.URLError as e:
            sys.exit(f"error: could not reach the GitHub API — {e.reason}")
        if not batch:
            break
        releases.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return releases


def render_table(releases: list[dict]) -> tuple[str, int]:
    """A markdown table body + the all-time download total."""
    rows = ["| Version | Published | Asset | Downloads |", "|---|---|---|---:|"]
    grand = 0
    for rel in releases:
        tag = rel.get("tag_name") or rel.get("name") or "—"
        published = (rel.get("published_at") or "")[:10]
        assets = rel.get("assets") or []
        if not assets:
            rows.append(f"| **{tag}** | {published} | _(no assets)_ | 0 |")
            continue
        subtotal = 0
        for i, a in enumerate(assets):
            count = int(a.get("download_count", 0))
            subtotal += count
            ver = f"**{tag}**" if i == 0 else ""
            pub = published if i == 0 else ""
            rows.append(f"| {ver} | {pub} | `{a.get('name', '?')}` | {count} |")
        rows.append(f"| | | **Total** | **{subtotal}** |")
        grand += subtotal
    return "\n".join(rows), grand


# #309: matches the "Last updated: ..." line emitted by build_doc() so it can
# be stripped before comparing old vs. new docs (the timestamp always differs
# and would otherwise defeat the workflow's git-diff commit-on-change guard).
LAST_UPDATED_RE = re.compile(r"^_Auto-generated by .*? Last updated: .*?\._$", re.MULTILINE)


def normalize(doc: str) -> str:
    """doc with the 'Last updated: ...' timestamp line blanked out, for comparison."""
    return LAST_UPDATED_RE.sub("", doc)


def build_doc(repo: str, releases: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (
        "# Download statistics\n\n"
        "_Auto-generated by [`scripts/download-stats.py`](../scripts/download-stats.py) "
        "(via the `download-stats.yml` workflow). Last updated: "
        f"{now}._\n\n"
        "Per-release GitHub asset download counts "
        f"(`release.assets[].download_count`) for "
        f"[`{repo}`](https://github.com/{repo}/releases).\n\n"
    )
    if not releases:
        return header + "_No releases published yet._\n"
    body, grand = render_table(releases)
    footer = f"\n\n**All-time total: {grand} download(s) across {len(releases)} release(s).**\n"
    return header + body + footer


def main() -> None:
    ap = argparse.ArgumentParser(description="Per-version GitHub Release download counts (#307).")
    ap.add_argument("--repo", help="owner/name (default: $GITHUB_REPOSITORY or the git origin)")
    ap.add_argument("--write", metavar="FILE", help="write the full markdown page to FILE instead of stdout")
    args = ap.parse_args()

    repo = resolve_repo(args.repo)
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    releases = fetch_releases(repo, token)
    doc = build_doc(repo, releases)

    if args.write:
        # #309: if only the "Last updated" timestamp would change, keep the old
        # file (with its old timestamp) so the workflow's `git diff --quiet`
        # commit-on-change guard stays meaningful.
        try:
            with open(args.write, encoding="utf-8") as f:
                old_doc = f.read()
        except (FileNotFoundError, OSError):
            old_doc = None
        if old_doc is not None and normalize(old_doc) == normalize(doc):
            doc = old_doc
        with open(args.write, "w", encoding="utf-8") as f:
            f.write(doc)
        total = sum(int(a.get("download_count", 0)) for r in releases for a in (r.get("assets") or []))
        print(f"Wrote {args.write}: {len(releases)} release(s), {total} download(s).")
    else:
        sys.stdout.write(doc)


if __name__ == "__main__":
    main()
